routes/web.php
<?php

use App\Models\Blog;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function(){
    $blogs = Blog::latest()->where('is_approved', 1)->get();
    return view('blogs.all', compact('blogs'));
});

Route::group(['middleware' => 'isAdmin', 'prefix' => 'admin'], function () {
    Route::get('/dashboard', 'App\Http\Controllers\AdminController@home')->name('admin.dashboard');
    Route::get('/users', 'App\Http\Controllers\AdminController@users')->name('admin.users');
    Route::get('/users/lists', 'App\Http\Controllers\AdminController@usersFetch')->name('admin.users.list');
    Route::get('/blogs', function () {
        return view('blogs.blogs');
    })->name('admin.blogs');
});

Route::get('/blogs/all', 'App\Http\Controllers\BlogController@allBlogs')->name('all.blogs');
Route::get('/blogs/{id}/status', 'App\Http\Controllers\BlogController@blogStatus')->middleware('auth');
Route::put('/blogs/{id}/status', 'App\Http\Controllers\BlogController@updateStatus')->middleware('auth');
Route::resources([
    'blogs' => \App\Http\Controllers\BlogController::class,
]);
Route::get('/dashboard', function () {
    return view('blogs.blogs');
})->name('dashboard')->middleware('auth');
require __DIR__ . '/auth.php';

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    use HasFactory;
    protected $fillable = [
        'title',
        'content',
        'author',
        'is_approved'
    ];

    public function User(){
        return $this->belongsTo(User::class, 'author');
    }
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Models\Blog;
use App\Models\User;
use ErrorException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Yajra\DataTables\Facades\DataTables;
use Illuminate\Support\Str;

class BlogController extends Controller
{
    private $user;
    public function __construct()
    {
        $this->middleware('auth')->only(['create', 'edit', 'store', 'update']);
        $this->middleware(function ($request, $next) {
            $this->user = Auth::user();
            if ($this->user && $this->user->user_type && in_array(explode('@', Route::currentRouteAction())[1], ['create', 'edit', 'store'])) {
                return redirect('admin/dashboard');
            }
            return $next($request);
        });
    }
    /**
     * Display a listing of user's blogs.
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        /**
         * check user type and return all blogs for admin or user's own blogs
         */
        // action button to control visibility of buttons based on role
        if ($this->user->user_type) {
            // check if author query param is set
            $author = $request->input('author');
            $blogs = $author ? Blog::latest()->where('author', $author)->get() : Blog::latest()->get();
        } else {
            $blogs = $this->user->blogs()->orderBy('updated_at', 'DESC');
        }
        $user = $this->user; // to pass to closure below
        return Datatables::of($blogs)
            ->editColumn('title', function ($data) {
                return Str::limit($data->title, 50);
            })
            ->editColumn('author', function ($data) {
                return User::find($data->author)->name;
            })
            ->editColumn('is_approved', function ($data) {
                return $data->is_approved ? 'Approved' : 'Un-approved';
            })
            ->addIndexColumn()
            ->addColumn('action', function ($row) use ($user) {
                if ($user->user_type) {
                    $actionBtn = '<a href="' . route('blogs.show', $row->id) . '" class="bg-green-500 px-4 py-2 text-xs font-semibold tracking-wider text-white rounded hover:bg-green-600">View</a> ';
                } else {
                    $actionBtn = '<a href="' . route('blogs.show', $row->id) . '" class="bg-green-500 px-4 py-2 text-xs font-semibold tracking-wider text-white rounded hover:bg-green-600">View</a> <a href="' . route('blogs.edit', $row->id) . '" class="bg-blue-500 px-4 py-2 text-xs font-semibold tracking-wider text-white rounded hover:bg-blue-600">Edit</a> ';
                }
                $actionBtn .= '<button data-blogId="'.$row->id.'" class="deleteBlog bg-red-500 px-4 py-2 text-xs font-semibold tracking-wider text-white rounded hover:bg-red-600">Delete</button>';
                $actionBtn = $actionBtn;
                return $actionBtn;
            })
            ->rawColumns(['action'])
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('blogs.edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Blog $blog)
    {
        // running validations on the incoming data
        $validated = $request->validate([
            'title' => 'required|max:255',
            'content' => 'required',
        ]);
        try {
            // throw new ErrorException('failed'); // test exception
            $newBlog = Blog::updateOrCreate(
                ['id' => $blog->id],
                [
                    'title' => $request->title,
                    'content' => $request->content,
                    'author' => $this->user->id
                ]
            );
            return back()->with('success', 'Success!');;
        } catch (\Throwable $th) {
            return back()->with(['error' => $th->getMessage()]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function show(Blog $blog)
    {
        return view('blogs.blog', compact('blog'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function edit(Blog $blog)
    {
        // check if the current user is the author of the $blog
        if ($blog->author !== $this->user->id) {
            return redirect('dashboard');
        }
        return view('blogs.edit', compact('blog'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Blog $blog)
    {
        // using the store method of the class to handle both update and create events
        $this->store($request, $blog);
        // or if there's no error send the user back to same edit screen with success message
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function destroy(Blog $blog)
    {
        if ($blog->author == $this->user->id || $this->user->user_type) {
           try {
               $deleteBlog = Blog::where('id', $blog->id)->delete();
               return response()->json([
                   'status' => true,
               ]);
           } catch (\Throwable $th) {
                return response()->json([
                    'status' => false,
                ]);
           }
        } else {
            return response()->json([
                'status' => false,
            ]);
        }
    }

    /**
     * load all blogs
     *
     * @return void
     */
    public function allBlogs()
    {
        $blogs = Blog::latest()->where('is_approved', 1)->get();
        return view('blogs.all', compact('blogs'));
    }

    /**
     * return the status of the blog - approved or un-approved
     *
     * @return void
     */
    public function blogStatus($id)
    {
        $blog = Blog::findOrFail($id);
        return response()->json([
            'status' => $blog->is_approved
        ]);
    }

    /**
     * update the status of the blog - approved or un-approved
     *
     * @return void
     */
    public function updateStatus($id)
    {
        $blog = Blog::findOrFail($id);
        $blog->is_approved = (Integer)!$blog->is_approved;
        $blog->save();
        return response()->json([
            'status' => $blog->is_approved
        ]);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/blogs/all.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('All Blogs') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            @if(!empty($blogs))
                @foreach ($blogs as $item)
                    <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg p-5 mb-5">
                        <h2 class="text-2xl mb-5">{{Str::limit($item->title, 50)}}</h2>
                        <a class="inline-block p-2 rounded-md shadow-sm hover:bg-blue-500 hover:text-white bg-blue-100"
                            href="{{route('blogs.show', $item->id)}}">Read More</a>
                    </div>
                @endforeach
            @else
            <h2 class="text-2xl mb-5">No blogs yet!</h2>
            @endif
        </div>
    </div>
</x-app-layout>

resources/views/blogs/blog.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Blog Summary') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <div class="flex" id="app">
                        <h1 class="text-2xl mb-5 mr-5">{{$blog->title}}</h1>
                        @if( Auth::user() && Auth::user()->user_type)
                        <Approve id="{{$blog->id}}" />
                        @else
                        @if (Auth::user() && $blog->author == Auth::user()->id)
                        <span class="text-green-500 px-4 py-2 text-xs font-semibold tracking-wider rounded">
                            <a href="{{route('blogs.edit', $blog->id)}}">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                                </svg>
                            </a>
                        </span>
                        @endif
                        @endif
                    </div>
                    <p class="italic">{{$blog->user->name}}</p>
                    <p>Last Updated at : {{date('d-m-Y H:i', strtotime($blog->updated_at))}}</p>
                    <form action="">

                    </form>
                    <hr class="my-2">
                    <div class="content">
                        {!!$blog->content!!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/blogs/blogs.blade.php
<x-app-layout>
    @push('styles')
    <style>
        button[disabled] {
            cursor: not-allowed;
            pointer-events: all !important;
            opacity: 0.5;
        }
    </style>
    @endpush
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ Auth::user() && !Auth::user()->user_type ? 'Manage your blogs' : 'Manage blogs'}}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            @if (Auth::user() && !Auth::user()->user_type)
            <div class="text-right">
                <a href="{{route('blogs.create')}}" class="inline-block mb-5 py-2 px-4 bg-green-500 text-white font-semibold rounded-lg shadow-md focus:outline-none">Add
                    Blog</a>
            </div>
            @endif
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <table class="table table-bordered yajra-datatable">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Title</th>
                                <th>Author</th>
                                <th>Approved?</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody class="text-center">
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(function() {
            var author = "{{ !empty(Request::get('author')) ? '?author='.Request::get('author') : ''  }}";
            var table = $('.yajra-datatable').DataTable({
                processing: true,
                serverSide: true,
                ajax: "/blogs" + author,
                columns: [{
                        data: 'DT_RowIndex',
                        name: 'DT_RowIndex',
                        orderable: false,
                        searchable: false
                    },
                    {
                        data: 'title',
                        name: 'title'
                    },
                    {
                        data: 'author',
                        name: 'author'
                    },
                    {
                        data: 'is_approved',
                        name: 'is_approved'
                    },
                    {
                        data: 'action',
                        name: 'action',
                        orderable: false,
                        searchable: false
                    },
                ]
            });
        });
        $(document).on('click', '.deleteBlog', function(e) {
            let verify = confirm('Are you sure you want to delete this blog?');
            if (verify) {
                $(this).attr('disabled', 'disabled')
                $.ajax({
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        id: $(this).data('blogid'),
                        _method: 'DELETE',
                        _token: "{{csrf_token()}}"
                    },
                    url: "{!! env('APP_URL').'/blogs/' !!}" + $(this).data('blogid'),
                }).done(function(data) {
                    if (data.status == true) {
                        alert('Blog post deleted!')
                    } else {
                        alert('Not authorized to delete this post!')
                    }
                    $('.deleteBlog[disabled]').removeAttr('disabled');
                    window.location.reload();
                })
            }
        })
    </script>
</x-app-layout>

resources/views/blogs/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ request()->routeIs('blogs.create') ? 'Add new blog' : 'Edit blog' }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            @if ($errors->any())
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
                <strong class="font-bold">Watch Out!</strong>
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            @if (Session::has('error'))
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
                {!!Session::get('error')!!}
            </div>
            @endif
            @if(Session::has('success'))
            <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
                {!!Session::get('success')!!}
            </div>
            @endif
            <form method="POST" action="{{empty($blog) ? route('blogs.store') : route('blogs.update', $blog->id)}}">
                @if (!empty($blog))
                @method('PUT')
                @endif
                {{ csrf_field() }}
                <div class="form-group text-right">
                    <button class="py-2 px-4 my-5 bg-green-500 text-white font-semibold rounded-lg shadow-md focus:outline-none">Save</button>
                </div>
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg p-5">
                    <div class="form-group mb-10">
                        <input required placeholder="Blog title" type="text" name="title" class="rounded-sm w-full" value="{{ !empty($blog) ? old('title', $blog->title) : ''}}">
                    </div>
                    <div class="form-group">
                        <input id="x" type="hidden" name="content">
                        <trix-editor input="x">
                            {!! (!empty($blog) ? old('content', $blog->content) : '') !!}
                        </trix-editor>
                    </div>
                </div>
            </form>
        </div>
    </div>
    @push('scripts')
    <script src="{{asset('plugins/trix-main/dist/trix.js')}}"></script>
    @endpush
    @push('styles')
    <link rel="stylesheet" href="{{asset('plugins/trix-main/dist/trix.css')}}" />
    @endpush
</x-app-layout>